# config.yaml

project:
  name: "Energy Systems Research Group: NDC2 Mitigation Technical Analysis"
  logo_path: "charts/common/ESRG sm colour.jpg"    # relative to project root

dev_mode: true

charts:
  include:       # if you leave this out or set to [], we auto-run all
    - fig1_total_emissions
    - fig2_shaded
    - fig3_ndc_emissions_by_sector
    - fig3b_ndc_emissions_by_sector
    - fig4_2035_stacked_bar_by_scenarios
    - fig5_base_reference_emissions

  exclude:
  - Secunda-Scop1-CO2 emission-All scenarios
  - Secunda-Scop1-CO2 emission-Scenario family
  - CO2 based on national inventory
  - Scunda FT's products
    

output:
  formats:    # file formats to write
    - png
    - svg
  resolutions:  # width & height (in pixels)
    dev:
      width: 800
      height: 600
    report:
      width: 1600
      height: 1200