# config.yaml

charts:
  # include:       # if you leave this out or set to [], we auto-run all
  #  - fig1_total_emissions
  exclude:
    - fig4_2035_stacked_bar_by_scenarios

output:
  formats:    # file formats to write
    - png
    - svg
  resolutions:  # width & height (in pixels)
    dev:
      width: 800
      height: 600
    report:
      width: 1600
      height: 1200